using UnityEngine;

public class Shot : MonoBehaviour
{
    public AudioClip clip;
    private AudioSource a;
    public GameObject bullet;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        a = GetComponent<AudioSource>();
        //a = AudioSource;
    }

    // Update is called once per frame
    void Update()
    {                   
        if (Input.GetKeyDown(KeyCode.Space))
        {
            Instantiate(bullet, transform.position, Quaternion.identity);
            a.PlayOneShot(clip);
        }
    }
}
